spring:
  application:
    name: meetingproject

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB

  datasource:
    url: jdbc:mysql://localhost:3306/meetingdb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: true
